Blocked revisions 767192,767231,767233,767235,767248,767256,767259,772691 via svnmerge
................
  r767192 | dkulp | 2009-04-21 11:42:58 -0400 (Tue, 21 Apr 2009) | 9 lines
  
  Merged revisions 767191 via svnmerge from 
  https://svn.apache.org/repos/asf/cxf/trunk
  
  ........
    r767191 | dkulp | 2009-04-21 11:40:48 -0400 (Tue, 21 Apr 2009) | 2 lines
    
    [CXF-2180] Catch throwable so ClassNotFoundException and NoClassDefFoundErrors can both be caught
  ........
................
  r767231 | dkulp | 2009-04-21 13:21:19 -0400 (Tue, 21 Apr 2009) | 9 lines
  
  Merged revisions 767191 via svnmerge from 
  https://svn.apache.org/repos/asf/cxf/trunk
  
  ........
    r767191 | dkulp | 2009-04-21 11:40:48 -0400 (Tue, 21 Apr 2009) | 2 lines
    
    [CXF-2180] Catch throwable so ClassNotFoundException and NoClassDefFoundErrors can both be caught
  ........
................
  r767233 | dkulp | 2009-04-21 13:23:47 -0400 (Tue, 21 Apr 2009) | 2 lines
  
  Didn't mean to commit that stuff.  Was looking at a patch.
................
  r767235 | dkulp | 2009-04-21 13:26:27 -0400 (Tue, 21 Apr 2009) | 2 lines
  
  Update release notes
................
  r767248 | dkulp | 2009-04-21 14:45:30 -0400 (Tue, 21 Apr 2009) | 8 lines
  
  Blocked revisions 767189 via svnmerge
  
  ........
    r767189 | dkulp | 2009-04-21 11:33:24 -0400 (Tue, 21 Apr 2009) | 2 lines
    
    Use the cached factories for the MessageModeOut stuff as well
  ........
................
  r767256 | dkulp | 2009-04-21 15:03:54 -0400 (Tue, 21 Apr 2009) | 1 line
  
  [maven-release-plugin] prepare release cxf-2.1.5
................
  r767259 | dkulp | 2009-04-21 15:05:45 -0400 (Tue, 21 Apr 2009) | 1 line
  
  [maven-release-plugin] prepare for next development iteration
................
  r772691 | dkulp | 2009-05-07 12:06:41 -0400 (Thu, 07 May 2009) | 84 lines
  
  Blocked revisions 767251,767263,767268,767271,767747,768350,768926,768938,769002,769027,769334,769736,769741,769784,769814,770220,770684,772137,772317,772620 via svnmerge
  
  ........
    r767251 | dkulp | 2009-04-21 14:56:13 -0400 (Tue, 21 Apr 2009) | 2 lines
    
    Add release notes for 2.2.1
  ........
    r767263 | dkulp | 2009-04-21 15:14:32 -0400 (Tue, 21 Apr 2009) | 2 lines
    
    Comment out the msv stuff as it's not working yet and the snapshots will block the release.
  ........
    r767268 | dkulp | 2009-04-21 15:52:47 -0400 (Tue, 21 Apr 2009) | 1 line
    
    [maven-release-plugin] prepare release cxf-2.2.1
  ........
    r767271 | dkulp | 2009-04-21 15:53:47 -0400 (Tue, 21 Apr 2009) | 1 line
    
    [maven-release-plugin] prepare for next development iteration
  ........
    r767747 | dkulp | 2009-04-22 20:50:58 -0400 (Wed, 22 Apr 2009) | 2 lines
    
    Exclude the simple frontend which sucks in soap.   Not needed in jaxrs.
  ........
    r768350 | sergeyb | 2009-04-24 12:19:48 -0400 (Fri, 24 Apr 2009) | 1 line
    
    JAXRS: minor update for DefaultValue for CookieParams be picked up, given that HttpHeaders never returns null
  ........
    r768926 | sergeyb | 2009-04-27 07:22:16 -0400 (Mon, 27 Apr 2009) | 1 line
    
    JAXRS: support for multiple matrix params in the last segment
  ........
    r768938 | sergeyb | 2009-04-27 07:47:44 -0400 (Mon, 27 Apr 2009) | 1 line
    
    JAXRS: no need for MethodDispatcher to use ConcurrentHashMap
  ........
    r769002 | eglynn | 2009-04-27 10:30:28 -0400 (Mon, 27 Apr 2009) | 1 line
    
    Adding PGP key for eglynn
  ........
    r769027 | sergeyb | 2009-04-27 11:29:37 -0400 (Mon, 27 Apr 2009) | 1 line
    
    JAXRS: minor updates to Cookie and ETag handlers
  ........
    r769334 | sergeyb | 2009-04-28 07:09:44 -0400 (Tue, 28 Apr 2009) | 1 line
    
    JAXRS HttpHeadersImpl updates (Locale construction, sorting media types), adding Content-Type to Message headers 
  ........
    r769736 | sergeyb | 2009-04-29 06:30:23 -0400 (Wed, 29 Apr 2009) | 1 line
    
    Fixing the test failure
  ........
    r769741 | sergeyb | 2009-04-29 06:55:04 -0400 (Wed, 29 Apr 2009) | 1 line
    
    JAXRS: Implementing ResponseBuilder.variants() plus various minor updates
  ........
    r769784 | sergeyb | 2009-04-29 09:35:46 -0400 (Wed, 29 Apr 2009) | 1 line
    
    JAXRS: updating UriBuilderImpl to support opaque URIs
  ........
    r769814 | sergeyb | 2009-04-29 12:16:56 -0400 (Wed, 29 Apr 2009) | 1 line
    
    JAXRS : retaining schemeSpecificPart in UriBuilderImpl.clone
  ........
    r770220 | sergeyb | 2009-04-30 09:38:26 -0400 (Thu, 30 Apr 2009) | 1 line
    
    JAXRS: support for custom invokers injected from Spring
  ........
    r770684 | sergeyb | 2009-05-01 09:59:19 -0400 (Fri, 01 May 2009) | 1 line
    
    JAXRS: support for parameter extensions on the client side
  ........
    r772137 | sergeyb | 2009-05-06 06:34:42 -0400 (Wed, 06 May 2009) | 1 line
    
    JAX-RS : adding JAXB-based XSLT provider
  ........
    r772317 | dkulp | 2009-05-06 11:45:00 -0400 (Wed, 06 May 2009) | 2 lines
    
    Remove unuseds SuppressWarnings
  ........
    r772620 | sergeyb | 2009-05-07 07:47:25 -0400 (Thu, 07 May 2009) | 1 line
    
    JAXRS: updating JAXB provider to use STAX readers/writers if available
  ........
................


git-svn-id: https://svn.apache.org/repos/asf/cxf/branches/2.0.x-fixes@772708 13f79535-47bb-0310-9956-ffa450edef68